### PR TITLE
Romcom2

### PR DESCRIPTION
**Pull request by Mr-Daniels-2025**
I have updated my changes to the code based on the past 5 zoom calls and collaboration with other groups.  I have added comments and recommended updates.  I have also compared our code.

### CODE REVIEW

**Comment by Mr-Daniels-2025** [comment]
Please review code for iteration-4 and collab on proposed changes.

**Review by Mr-Daniels-2025 — COMMENTED** [review]
I have rewritten this code based on my previous 5 versions.  I have also written Iteration-4 so that it NOW works correctly.  I was not able to gain a review on this code on Sept 4 or 5...so I will have to submit it as a 100% finalized product.

**Review by EvanSSwanson — CHANGES_REQUESTED** [review]
We should take care of all these comments for the final version. Otherwise if it all works, then that's great

**Review by Mr-Daniels-2025 — COMMENTED** [review]
Looks good.

**Review by EvanSSwanson — APPROVED** [review]

**Pull request merged**
